version: "3"

services:
  nfs:
    image: itsthenetwork/nfs-server-alpine
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - ./nfsshare:/nfsshare
    environment:
      SHARED_DIRECTORY: /nfsshare
